version: '3.4'
services:
  app:
    build:
      context: ./agents/agent-nodejs
    container_name: agent-nodejs
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    ports:
      - "${APPLICATION_PORT}:8000"add
    volumes:
      - ./agents/agent-nodejs/.:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
