version: '3.4'
services:
  mysql:
    image: mysql:oracle
    container_name: forest_example_mysql
    ports:
      - '5443:3306'
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

volumes:
  mysql-data:
    driver: local
