version: '3.4'
services:
  app:
    build:
      context: ./agents/django_agent
    container_name: django_agent
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    volumes:
      - ./agents/django_agent/.:/usr/src/app
